export const addrStatuses = {
    "IDLE": "IDLE",
    "FETCHING_ADDRESS": "FETCHING_ADDRESS",
    "FETCHING_ENS": "FETCHING_ENS",
    "INVALID_ADDRESS": "INVALID_ADDRESS",
    "INVALID_ENS": "INVALID_ENS",
    "ADDRESS_FOUND": "ADDRESS_FOUND",
}

